### ISSUE TITLE
Nest Feature: controls for charts

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/toshi-nest#55]
We want a widget on the chart that opens a box that can contain chart controls. Those controls will be customized by use to allow the user some control over chart behavior and appearance (e.g. switch between linear and log scale). The widget would be a faint gear icon in the upper right corner of the chart that when clicked opens up the chart controls

**Comment by chrisbc** [comment]
This work was done by @benjamineac  was done in https://github.com/GNS-Science/kororaa/pull/75 and https://github.com/GNS-Science/kororaa/pull/77
